### ISSUE TITLE
market1501_trained.pth.tar load error from your google drive download link

### ISSUE THREAD

**Issue by geyutang** [OasisYang/SSG#11]
Following is my problem, I download your pretrained model from google drive. 
I load dukemtmc.pth.tar successful but fall at market1501.
Any suggestion about this? Anyway, I could retrain a market1501 model using source_train.py
Thanks!

Files already downloaded and verified
Market1501 dataset loaded
  subset   | # ids | # images
  ---------------------------
  train    |   676 |    11744
  val      |    75 |     1192
  trainval |   751 |    12936
  query    |   750 |     3368
  gallery  |   751 |    15913
Files already downloaded and verified
DukeMTMC dataset loaded
  subset   | # ids | # images
  ---------------------------
  train    |   632 |    14923
  val      |    70 |     1599
  trainval |   702 |    16522
  query    |   702 |     2228
  gallery  |  1110 |    17661
Resuming checkpoints from finetuned model on another dataset...

Traceback (most recent call last):
  File "/home/node3/xxx/SSG/selftraining.py", line 405, in <module>
    main(parser.parse_args())
  File "/home/node3/xxx/SSG/selftraining.py", line 136, in main
    checkpoint = load_checkpoint(args.resume)
  File "/home/node3/xxx/SSG/reid/utils/serialization.py", line 34, in load_checkpoint
    checkpoint = torch.load(fpath)['state_dict']
  File "/home/node3/anaconda3/envs/py36_cu10/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/node3/anaconda3/envs/py36_cu10/lib/python3.6/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)

**Comment by wpffs** [comment]
Hi~ I meet the same problem with you. Have you solved it？ and please share the method if you could

**Comment by geyutang** [comment]
The author gave this link https://github.com/OasisYang/SSG/issues/2#issuecomment-534236168 for solving this.
