### ISSUE TITLE
Error on source_train.py

### ISSUE THREAD

**Issue by mahfujur1** [OasisYang/SSG#15]
Hi,

I run the code and got the following error. 

Traceback (most recent call last):
  File "source_train.py", line 311, in <module>
    main(parser.parse_args())
  File "source_train.py", line 237, in main
    rank_score = evaluator.evaluate(val_loader, dataset.val, dataset.val)
  File "/media/mahfuj/DATA/preid/SSG-master/reid/evaluators.py", line 190, in evaluate
    features, _ = extract_features(self.model, data_loader, print_freq=self.print_freq)
  File "/media/mahfuj/DATA/preid/SSG-master/reid/evaluators.py", line 28, in extract_features
    outputs = extract_cnn_feature(model, imgs, for_eval)
  File "/media/mahfuj/DATA/preid/SSG-master/reid/feature_extraction/cnn.py", line 16, in extract_cnn_feature
    outputs = model(inputs, for_eval)[0]
  File "/home/mahfuj/pytorch_new_python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mahfuj/pytorch_new_python3/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/mahfuj/pytorch_new_python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

**Comment by OasisYang** [comment]
You can simply remove the for_eval argument in SSG-master/reid/feature_extraction/cnn.py.
And there maybe some bugs in source_train.py, please refer to [DomainAdaptiveReID](https://github.com/LcDog/DomainAdaptiveReID) to obtained the pretrained model or just use the pretrained model provided by us.
