### ISSUE TITLE
 I ran into a problem when I tried to run source_train.py

### ISSUE THREAD

**Issue by moyu284** [OasisYang/SSG#25]
Traceback (most recent call last):
  File "source_train.py", line 315, in <module>
    main(parser.parse_args())
  File "source_train.py", line 241, in main
    rank_score = evaluator.evaluate(val_loader, dataset.val, dataset.val)
  File "/data0/network/SSG-master/SSG-master/reid/evaluators.py", line 190, in evaluate
    features, _ = extract_features(self.model, data_loader, print_freq=self.print_freq)
  File "/data0/network/SSG-master/SSG-master/reid/evaluators.py", line 28, in extract_features
    outputs = extract_cnn_feature(model, imgs, for_eval)
  File "/data0/network/SSG-master/SSG-master/reid/feature_extraction/cnn.py", line 16, in extract_cnn_feature
    outputs = model(inputs, for_eval)[0]
  File "/home/dongwh/anaconda3/envs/SSG/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dongwh/anaconda3/envs/SSG/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/dongwh/anaconda3/envs/SSG/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/dongwh/anaconda3/envs/SSG/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/dongwh/anaconda3/envs/SSG/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/dongwh/anaconda3/envs/SSG/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

**Comment by OasisYang** [comment]
The source_train.py has some problem, but I don't have time to review it. I have removed it and I recommend you to refer this [repo.](https://github.com/LcDog/DomainAdaptiveReID).
